### ISSUE TITLE
Tags for GProts

### ISSUE THREAD

**Issue by fredericobormann** [fsinfuhh/mafiasi#11]
It would be very nice to have labels or tags for GProts, so you can tag them for example as "Probeklausur", "Bonusklausur" or something similar. Hereby, there would be the possibility to filter them by tags and find the GProt you are looking for more easily.

**Comment by timonegk** [comment]
The feature was implemented in #14, the filter does not exist yet but I think that it is not really necessary because the gprot overview is very clear now. If you disagree, feel free to reopen the issue.
