### ISSUE TITLE
Return the User to the Etherpad Overview page when logging in from Etherpad

### ISSUE THREAD

**Issue by 8fuhst** [fsinfuhh/mafiasi#129]
# Expected Behavior

When you're accessing Etherpad without being logged in, and then log in from there, you are returned to your personal overview of etherpads and group pads.

# Actual Behavior

When you're accessing Etherpad without being logged in, and then log in from there, you are returned to the Mafiasi Dashboard.

**Comment by timonegk** [comment]
Closed in #133.
