### ISSUE TITLE
Link to university mail is wrong

### ISSUE THREAD

**Issue by ftsell** [fsinfuhh/mafiasi#78]
The link to university here is wrong:
![image](https://user-images.githubusercontent.com/12398140/162220669-5ae44c20-0cd5-4aad-b1ff-9ba44ba77658.png)

It still points to surfmail but should point to https://exchange.uni-hamburg.de/

**Comment by timonegk** [comment]
This is not correct. Exchange can only be used by people who have been employed by the university at any point. Everybody else continues to use Surfmail (cf. [here](https://www.rrz.uni-hamburg.de/services/e-mail/fuer-studierende.html)).
